<!DOCTYPE html>
<html>
	<head>
		<title>404</title>
		<style>
			* {
				padding: 0;	
				margin: 0;
				font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;
			}
			body, html {
				width: 100%;
				height: 100vh;
				background-color: #f0f0f0;
				text-align: center;
			}
			span {
				line-height: 100vh;
				font-size: 25vh;
			}
		</style>
	</head>
	<body>
		<span>404</span>
	</body>
</html>