<!DOCTYPE html>
<html lang="ru">
<head>
	<title><?=Lang::getText('bugtracker')?></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/work/css/main.css">
	<link rel="stylesheet" type="text/css" href="/work/css/float-dropdown-menu.css">
	<link rel="stylesheet" type="text/css" href="/work/css/loading.css">
	<script src="/work/consts.js"></script>
	<script src="/work/lang/ru.js"></script>
	<script src="/work/js/main.js"></script>
	<script src="/work/js/apirequest.js"></script>
	<script src="/work/js/http_request.js"></script>
	<script src="/work/js/bugtracker.js"></script>
	<script src="/work/js/dropdown.js"></script>
	<script>Bugtracker.getPost(getGET("post"))</script>
</head>
<body>
	<div class="wrapper">
		<?php include __DIR__ . '/header.phtml' ?>
		<div class="content">
			<div class="column">
				<div id="content" class="paper-list no-padding">
					<div class="spinner loading-box">
						<div class="bounce1"></div>
						<div class="bounce2"></div>
						<div class="bounce3"></div>
					</div>
				</div>
				<div class="paper-list no-padding m24t">
					<div class="paper-head"><?=Lang::getText('comments')?> <span id="commentsCount" class="gray">0</span></div>
					<div id="comments" class="comments-block"><div style="height: 100px; padding: 12px; text-align: center; box-sizing:border-box;">
							<span style="line-height: 76px;"class="gray"><?=Lang::getText('nobodyCommented')?></span>
						</div>
					</div>
					<?php if ($user !== false) { ?>
					<textarea class="comment-posting-form" placeholder="<?=Lang::getText('yourComment')?>" id="comment-text-input"></textarea>
					<div class="paper-foot">
						<?php if ($user->hasRightTo('moderateBugs')) { ?>
						<div id="dropdownSelector"></div>
						<script>
							var reportNewStatusSelector = new DropdownSelector(document.getElementById("dropdownSelector"), [
								{
									key: "placeholder",
									value: l("bt_report_new_status")
								},
								{
									key: "open",
									value: l("bt_status_open")
								},
								{
									key: "closed",
									value: l("bt_status_closed")
								},
								{
									key: "waiting",
									value: l("bt_status_waiting")
								},
								{
									key: "in_process",
									value: l("bt_status_in_process")
								},
								{
									key: "fixed",
									value: l("bt_status_fixed")
								},
								{
									key: "do_not_change",
									value: l("bt_do_not_change_status")
								}
							]);
						</script>
						<?php } ?>
						<button class="right-hand-side button-red" onclick="Bugtracker.commentSend()"><?=Lang::getText('send')?></button>
					<?php } ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
