<!DOCTYPE html>
<html lang="ru">
<head>
	<title><?=Lang::getText('allPosts')?> | <?=Lang::getText('bugtracker')?></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/work/css/float-dropdown-menu.css">
	<link rel="stylesheet" type="text/css" href="/work/css/main.css">
	<link rel="stylesheet" type="text/css" href="/work/css/loading.css">
	<script src="/work/consts"></script>
	<script src="/work/lang/ru"></script>
	<script src="/work/js/main.js"></script>
	<script src="/work/js/http_request.js"></script>
	<script src="/work/js/bugtracker.js"></script>
	<script>drawBugtrackerMainPage()</script>
</head>
<body>
	<div class="wrapper">
		<?php include __DIR__ . '/header.phtml' ?>
		<div class="content">
			<div class="column">
				<div class="paper-list no-padding">
					<div class="paper-head">Все отчёты<?php if ($user !== false) { ?><a href="/bugtracker?act=add" class="button-red right-hand-side">Отправить</a><?php } ?></div>
					<div id="content">
						<div class="spinner loading-box">
							<div class="bounce1"></div>
							<div class="bounce2"></div>
							<div class="bounce3"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
