<!DOCTYPE html>
<html lang="ru">
<head>
	<title><?=Lang::getText('bugtracker')?></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/work/css/main.css">
	<link rel="stylesheet" type="text/css" href="/work/css/float-dropdown-menu.css">
	<script src="/work/consts"></script>
	<script src="/work/lang/ru"></script>
	<script src="/work/js/main.js"></script>
	<script src="/work/js/apirequest.js"></script>
	<script src="/work/js/http_request.js"></script>
	<script src="/work/js/bugtracker.js"></script>
	<script src="/work/js/dropdown.js"></script>
	<script>getPost({id: getGET("post")})</script>
</head>
<body>
	<div class="wrapper">
		<?php if ($user !== false) { ?>
			<div class="top-profile-menu" id="topProfileMenu">
				<a class="top-profile-menu-item"><?=Lang::getText('profile')?></a>
				<a class="top-profile-menu-item"><?=Lang::getText('settings')?></a>
				<a class="top-profile-menu-item" onclick="goOut()"><?=Lang::getText('exit')?></a>
				<?php if ($user->hasRightTo('testApi')) { ?>
				<div class="top-profile-menu-divider"></div>
				<a class="top-profile-menu-item" href="/test"><?=Lang::getText('apiTestMethodRequest')?></a>
				<?php } ?>
			</div>
		<?php } ?>
		<header>
			<div class="headline-wrapper">
				<div class="headline-elements-container">
					<div class="partitions">
						<span class="headline-elem"><a href="/main"><?=Lang::getText('mainPage')?></a></span>
						<?php if ($user !== false) { ?><span class="headline-elem"><a href="/learn"><?=Lang::getText('learn')?></a></span><?php } ?>
						<span class="headline-elem"><a href="#"><?=Lang::getText('INeedHelp')?></a></span>
						<span class="headline-elem"><a href="#"><?=Lang::getText('aboutUs')?></a></span>
						<span class="headline-elem"><a href="/bugtracker"><?=Lang::getText('bugtracker')?></a></span>
						<a href="/index" id="goToMainPage" hidden></a>
					</div>
				</div>
				<div <?= ($user !== false) ? 'class="account-settings" onclick="openTopProfileMenu()"' : 'class="top-stuff-container"'?>>
					<?php if ($user === false) { ?>
						<span class="headline-elem">
							<a href="/login"><?=Lang::getText('logIn')?></a>
						</span>
						<div class="dropdown-lang-select" style="float:right;">
							<button class="dropbtn russian">&#160;</button>
							<div class="dropdown-content">
								<a class="english" href="#">&#160;</a>
								<a class="russian" href="#">&#160;</a>
								<a class="belarusian" href="#">&#160;</a>
							</div>
						</div>
					<?php } else { ?>
						<span class="headline-elem">
							<span class="top-user-name"><?=$user->getName(true)?></span>
							<img class="profile-pic" src="<?=$user->getProfilePicture()?>">
							<span class="top-profile-arrow"></span>
						</span>
					<?php } ?>
				</div>
			</div>
		</header>
		<div class="content">
			<div class="column">
				<div id="content" class="paper-list no-padding">
					
				</div>
				<div class="paper-list no-padding m24t">
					<div class="paper-head"><?=Lang::getText('comments')?> <span id="commentsCount" class="gray">0</span></div>
					<div id="comments" class="comments-block">
						<div style="height: 100px; padding: 12px; text-align: center; box-sizing:border-box;">
							<span style="line-height: 76px;"class="gray"><?=Lang::getText('nobodyCommented')?></span>
						</div>
					</div>
					<?php if ($user !== false) { ?>
					<textarea class="comment-posting-form" placeholder="<?=Lang::getText('yourComment')?>" id="comment-text-input"></textarea>
					<div class="paper-foot">
						<?php if ($user->hasRightTo('moderateBugs')) { ?>
						<div id="dropdownSelector"></div>
						<script>
							var reportNewStatusSelector = new DropdownSelector(document.getElementById("dropdownSelector"), [
								{
									key: "placeholder",
									value: l("bt_report_new_status")
								},
								{
									key: "open",
									value: l("bt_status_open")
								},
								{
									key: "closed",
									value: l("bt_status_closed")
								},
								{
									key: "waiting",
									value: l("bt_status_waiting")
								},
								{
									key: "in_process",
									value: l("bt_status_in_process")
								},
								{
									key: "fixed",
									value: l("bt_status_fixed")
								},
								{
									key: "do_not_change",
									value: l("bt_do_not_change_status")
								}
							]);
						</script>
						<?php } ?>
						<button class="right-hand-side button-red" onclick="commentSend()"><?=Lang::getText('send')?></button>
					<?php } ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
