<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title><?=Lang::getText($title)?></title>
	<link rel="stylesheet" type="text/css" href="/work/css/main.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="/work/js/main.js"></script>
	<?=$insertToHead?>
</head>
<body>
	<div class="wrapper">
		<header>
			<div class="headline-wrapper">
				<div class="headline-elements-container">
					<div class="partitions">
						<span class="headline-elem"><a href="/main"><?=Lang::getText('mainPage')?></a></span>
						<span class="headline-elem"><a href="#"><?=Lang::getText('learn')?></a></span>
						<span class="headline-elem"><a href="#"><?=Lang::getText('INeedHelp')?></a></span>
						<span class="headline-elem"><a href="#"><?=Lang::getText('aboutUs')?></a></span>
						<span class="headline-elem"><a href="/bugtracker"><?=Lang::getText('bugtracker')?></a></span>
						<a href="/index" id="goToMainPage" hidden></a>
					</div>
				</div>
				<div class="account-settings">
					<?php if ($user === false) { ?>
						<span class="headline-elem">
							<a href="/login"><?=Lang::getText('logIn')?></a>
						</span>
						<div class="dropdown-lang-select" style="float:right;">
							<button class="dropbtn russian">&#160;</button>
							<div class="dropdown-content">
								<a class="english" href="#">&#160;</a>
								<a class="russian" href="#">&#160;</a>
								<a class="belarusian" href="#">&#160;</a>
							</div>
						</div>
					<?php } else { ?>
						<span class="headline-elem">
							<a href="#" onclick="goOut()" class="mr10px"><?=Lang::getText('exit')?></a>
							<img class="profile-pic" src="<?=$user->getProfilePicture()?>">
						</span>
					<?php } ?>
				</div>
			</div>
		</header>
		<div class="content"><div class="column">
				<div id="content" class="paper-list<?=(isset($content_no_padding)?' no-padding':'')?>"><?=$content?></div>
		</div></div>
		<div class="footer">
			<div class="column">
				<div class="mini-column">Sample text</div>
			</div>
		</div>
	</div>
</body>
</html>