<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>Belmova</title>
	<link rel="stylesheet" type="text/css" href="/work/css/learn.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="/work/js/main.js"></script>
	<script src="/work/js/http_request.js"></script>
	<script src="/work/js/caret_position.js"></script>
	<script src="/work/js/learn.js"></script>
</head>
<body>
	<div class="wrapper">
		<header>
			<div class="column">
				<div class="header-wrapper">
					<span class="backbutton" onclick="goUpperPage()">
						<span class="backbutton-arrow"></span> Назад
					</span>
					<span class="right-hand-side vlightgray fw600 cpointer" onclick="goToConstructor()">Конструктор</span>
				</div>
			</div>
		</header>
		<div class="content">
			<div class="column" id="content">
				<div class="c-wrapper p12">
					<table>
						<tbody>
							<tr>
								<td class="lcol"><label class="no-margin-bottom">Тип задания</label></td>
								<td class="rcol">
									<div class="dropdown-act-select">
										<div class="dropfield"><span id="typeSelector">Выберите тип задания</span><span class="dropdown-arrow"></span></div>
										<div class="dropdown-content">
											<div class="dropdown-elem" id="sel1elem1" onclick="onDropdownSelect(this)">
												Прочитать правило
											</div>
											<div class="dropdown-elem" id="sel1elem2" onclick="onDropdownSelect(this)">
												Составить перевод
											</div>
											<div class="dropdown-elem" id="sel1elem3" onclick="onDropdownSelect(this)">
												Написать перевод
											</div>
											<div class="dropdown-elem" id="sel1elem4" onclick="onDropdownSelect(this)">
												Ответить на вопрос
											</div>
										</div>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					<!--Here's constructor activities-->
					<table id="readTheRule" hidden>
						<tbody>
							<tr>
								<td class="lcol">
									<label class="no-margin-bottom">Заголовок</label>
								</td>
								<td class="rcol">
									<input type="text" class="text-field">
								</td>
							</tr>
							<tr>
								<td class="lcol">
									<label class="no-margin-bottom">Текст</label>
								</td>
								<td class="rcol">
									<textarea rows="10" class="text-field textarea"></textarea>
								</td>
							</tr>
						</tbody>
					</table>
					<table id="makeTranslation" hidden>
						<tbody>
							<tr>
								<td class="lcol">
									<label class="no-margin-bottom">Предложение</label>
								</td>
								<td class="rcol">
									<input type="text" class="text-field">
								</td>
							</tr>
							<tr>
								<td class="lcol">
									<label class="no-margin-bottom">Слова</label>
								</td>
								<td class="rcol">
									<div class="text-field text-div" id="wordsInput" onclick="placeCaretAtEnd(this)" onchange="onWordsContainerChange(this)" contenteditable></div>
									<script>initWordsInput()</script>
								</td>
							</tr>
							<tr>
								<td class="lcol">
									<label class="no-margin-bottom">Правильные варианты перевода</label>
								</td>
								<td class="rcol">
									
								</td>
							</tr>
						</tbody>
					</table>
					<table id="writeTranslation" hidden>
						<tbody>
							<tr>
								<td class="lcol">
									<label class="no-margin-bottom">Предложение</label>
								</td>
								<td class="rcol">
									<input type="text" class="text-field">
								</td>
							</tr>
							<tr>
								<td class="lcol">
									<label class="no-margin-bottom">Правильные варианты перевода</label>
								</td>
								<td class="rcol">
									
								</td>
							</tr>
						</tbody>
					</table>
					<table id="answerTheQuestion" hidden>
						<tbody>
							<tr>
								<td class="lcol">
									<label class="no-margin-bottom">Вопрос</label>
								</td>
								<td class="rcol">
									<input type="text" class="text-field">
								</td>
							</tr>
							<tr>
								<td class="lcol">
									<label class="no-margin-bottom">Варианты ответа</label>
								</td>
								<td class="rcol">
									
								</td>
							</tr>
						</tbody>
					</table>
					<!--Now it's enough-->
				</div>
			</div>
		</div>
	</div>
</body>
</html>