<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>Belmova</title>
	<link rel="stylesheet" type="text/css" href="/work/css/learn.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="/work/js/main.js"></script>
	<script src="/work/js/http_request.js"></script>
	<script src="/work/js/learn.js"></script>
	<script>init()</script>
</head>
<body>
	<div class="wrapper">
		<header>
			<div class="column">
				<div class="header-wrapper">
					<span class="backbutton" onclick="goMainPage()">
						<span class="backbutton-arrow"></span> Назад
					</span>
					<span class="right-hand-side vlightgray fw600">Конструктор</span>
				</div>
			</div>
		</header>
		<div class="content">
			<div class="column" id="content">
				
			</div>
		</div>
	</div>
</body>
</html>