<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title><?=Lang::getText('allLessons');?> | <?=Lang::getText('learn');?></title>
	<link rel="stylesheet" type="text/css" href="/work/css/learn.css">
	<link rel="stylesheet" type="text/css" href="/work/css/main.css">
	<link rel="stylesheet" type="text/css" href="/work/css/loading.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="/work/consts.js"></script>
	<script src="/work/lang/ru.js"></script>
	<script src="/work/js/sidebar.js"></script>
	<script src="/work/js/main.js"></script>
	<script src="/work/js/http_request.js"></script>
	<script src="/work/js/learn.js"></script>
	<script>init()</script>
</head>
<body>
	<div class="wrapper">
		<?php include 'header.phtml' ?>
		<!--<header>
			<div class="column">
				<div class="header-wrapper">
					<span class="backbutton" onclick="goMainPage()">
						<span class="backbutton-arrow"></span> Назад
					</span>
					<span class="right-hand-side vlightgray fw600 cpointer" onclick="goToConstructor()">Конструктор</span>
				</div>
			</div>
		</header>-->
		<div class="content">
			<div class="column">
				<div class="piece-of-paper alert-block">
					<span class="alpha-letter"></span>
					<span class="alert-message">
						<span class="alert-message-title"><?=Lang::getText('itIsAlpha')?></span>
						<span class="alert-message-text"><?=Lang::getText('sendReportsThere')?></span>
					</span>
				</div>
				<div id="content">
					<div class="spinner loading-box">
						<div class="bounce1"></div>
						<div class="bounce2"></div>
						<div class="bounce3"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php if ($user->hasRightTo('createLessons')) { ?>
	<script>
		new Sidebar([
			{
				text: l("allLessons"),
				onselect: function() {
					goTo(URL + "learn");
				},
				selected: true
			},
			{
				text: l("constructor"),
				onselect: function() {
					goTo(URL + "learn?act=constructor");
				}	
			}
		]);
	</script>
	<?php } ?>
</body>
</html>