<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>Belmova</title>
	<link rel="stylesheet" type="text/css" href="/work/css/lesson.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="/work/consts"></script>
	<script src="/work/lang/ru"></script>
	<script src="/work/js/main.js"></script>
	<script src="/work/js/apirequest.js"></script>
	<script src="/work/js/http_request.js"></script>
	<script src="/work/js/caret_position.js"></script>
	<script src="/work/js/learn.js"></script>
	<script src="/work/js/lesson.js"></script>
</head>
<body>
	<div class="cover" id="loading">
		<div class="spinner">
			<div class="bounce1"></div>
			<div class="bounce2"></div>
			<div class="bounce3"></div>
		</div>
	</div>
	<div class="cover" id="win" hidden>

	</div>
	<div class="column" style="max-height: 20px">
		<div class="head">
			<div class="top-cross" onclick="goTo('learn')"></div>
			<div class="top-progress-bar-bkg"></div>
			<div class="top-progress-bar-container"><div class="top-progress-bar" id="progressBar" style="width: 0"></div></div>
		</div>
	</div>
	<div class="column">
		<div class="small-column">
			<div class="task-container">
				<div class="task-title" id="taskTitle"></div>
				<div class="task-text" id="taskText"></div>
				<div class="active" id="activeZone"></div>
			</div>
		</div>
	</div>
	<div class="foot">
		<div class="column">
			<button class="miss"><?=Lang::getText('skip')?></button>
			<button class="check" id="checkButton"><?=Lang::getText('check')?></button>
		</div>
	</div>
	<div class="well-done" id="successNotifier" hidden>
		<div class="column">
			<span class="checked-mark"></span>
			<div class="well-done-text"><?=Lang::getText('correct')?>
				<span class="smaller" id="onSuccessText"></span>
				<span class="smaller report-green"><?=Lang::getText('report')?></span>
			</div>
			<button class="check" id="onSuccessButton"><?=Lang::getText('next')?></button>
		</div>
	</div>
	<div class="bad-done" id="mistakeNotifier" hidden>
		<div class="column">
			<span class="cross-mark"></span>
			<div class="bad-done-text"><?=Lang::getText('correctAnswer')?>:
				<span class="smaller" id="onMistakeText"></span>
				<span class="smaller report"><?=Lang::getText('report')?></span>
			</div>
			<button class="red" id="onMistakeButton"><?=Lang::getText('next')?></button>
		</div>
	</div>
	<script>
		var lesson = new Lesson(getGET("lid"), {
			onMistakeNotifier: document.getElementById("mistakeNotifier"),
			onMistakeText: document.getElementById("onMistakeText"),
			onMistakeButton: document.getElementById("onMistakeButton"),
			onSuccessNotifier: document.getElementById("successNotifier"),
			onSuccessText: document.getElementById("onSuccessText"),
			onSuccessButton: document.getElementById("onSuccessButton"),
			taskTitle: document.getElementById("taskTitle"),
			progressBar: document.getElementById("progressBar"),
			taskText: document.getElementById("taskText"),
			activeZone: document.getElementById("activeZone"),
			checkButton: document.getElementById("checkButton"),
			loadingScreen: document.getElementById("loading"),
			winScreen: document.getElementById("win")
		});
	</script>
</body>
</html>