<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>Belmova</title>
	<link rel="stylesheet" type="text/css" href="/work/css/learn.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="/work/js/main.js"></script>
	<script src="/work/js/http_request.js"></script>
	<script src="/work/js/caret_position.js"></script>
	<script src="/work/js/learn.js"></script>
</head>
<body>
	<div class="wrapper">
		<header>
			<div class="column">
				<div class="header-wrapper">
					<span class="backbutton" onclick="goUpperPage()">
						<span class="backbutton-arrow"></span> Назад
					</span>
				</div>
			</div>
		</header>
		<div class="content">
			<div class="column">
				<div class="c-wrapper p12">
					<span class="what-to-do" id="whatToDo"></span>
					<div class="exercise">
						
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>init_lesson()</script>
</body>
</html>