<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title><?=Lang::getText('entrance')?></title>
	<link rel="stylesheet" type="text/css" href="/work/css/main.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/work/css/float-dropdown-menu.css">
	<script src="/work/consts"></script>
	<script src="/work/js/http_request.js"></script>
	<script src="/work/js/login.js"></script>
</head>
<body>
	<div class="wrapper">
		<header>
			<div class="headline-wrapper">
				<div class="headline-elements-container">
					<div class="partitions">
						<span class="headline-elem"><a href="/main"><?=Lang::getText('mainPage')?></a></span>
						<span class="headline-elem"><a href="#"><?=Lang::getText('learn')?></a></span>
						<span class="headline-elem"><a href="#"><?=Lang::getText('INeedHelp')?></a></span>
						<span class="headline-elem"><a href="#"><?=Lang::getText('aboutUs')?></a></span>
						<span class="headline-elem"><a href="/bugtracker"><?=Lang::getText('bugtracker')?></a></span>
					</div>
				</div>
				<div class="account-settings">
					<span class="headline-elem"><a href="/login"><?=Lang::getText('logIn')?></a></span>
					<div class="dropdown" style="float:right;">
						<button class="dropbtn russian">&#160;</button>
						<div class="dropdown-content">
							<a class="english" href="#">&#160;</a>
							<a class="russian" href="#">&#160;</a>
							<a class="belarusian" href="#">&#160;</a>
						</div>
					</div>
				</div>
			</div>
		</header>
		<div class="content">
			<div class="login-window">
				<div id="content" class="paper-list">
					<a id="linkToMainPage" href="/index" hidden></a>
					<label for="identificator"><?=Lang::getText('loginOrEmail')?></label>
					<input id="identificator" type="text" class="text-field">
					<div class="incorrect-notification-container"><span id="identificator-incorrect" hidden><label for="identificator" class="red-text"><?=Lang::getText('incorrectIdentificator')?></label></span></div>
					
					<label for="password"><?=Lang::getText('password')?></label>
					<input id="password" type="password" class="text-field">
					<div class="incorrect-notification-container"><span id="password-incorrect" hidden><label for="password" class="red-text" ><?=Lang::getText('incorrectPassword')?></label></span></div>
					
					<input type="submit" onclick="handleButtonClick()" class="confirm-button" value="<?=Lang::getText('logIn')?>">
				</div>
				<span class="signuplink" id="signuplink">Впервые у нас? <a href="#" onclick="goToTokenInput()">Мгновенная регистрация</a></span>
			</div>
		</div>
	</div>
</body>
</html>