<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title><?=Lang::getText('entrance')?></title>
	<link rel="stylesheet" type="text/css" href="/work/css/main.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/work/css/float-dropdown-menu.css">
	<script src="/work/consts.js"></script>
	<script src="/work/js/http_request.js"></script>
	<script src="/work/js/login.js"></script>
</head>
<body>
	<div class="wrapper">
		<?php include __DIR__ . '/header.phtml' ?>
		<div class="content">
			<div class="login-window">
				<div id="content" class="paper-list">
					<a id="linkToMainPage" href="/index" hidden></a>
					<label for="identificator"><?=Lang::getText('loginOrEmail')?></label>
					<input id="identificator" type="text" class="text-field">
					<div class="incorrect-notification-container"><span id="identificator-incorrect" hidden><label for="identificator" class="red-text"><?=Lang::getText('incorrectIdentificator')?></label></span></div>
					
					<label for="password"><?=Lang::getText('password')?></label>
					<input id="password" type="password" class="text-field">
					<div class="incorrect-notification-container"><span id="password-incorrect" hidden><label for="password" class="red-text" ><?=Lang::getText('incorrectPassword')?></label></span></div>
					
					<input type="submit" onclick="handleButtonClick()" class="confirm-button" value="<?=Lang::getText('logIn')?>">
				</div>
				<span class="signuplink" id="signuplink">Впервые у нас? <a href="#" onclick="goToTokenInput()">Мгновенная регистрация</a></span>
			</div>
		</div>
	</div>
</body>
</html>