<!DOCTYPE html>
<html lang="ru">
<head>
	<title><?=Lang::getText('testRequest')?> | <?=Lang::getText('forAdmins')?></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/work/css/float-dropdown-menu.css">
	<link rel="stylesheet" type="text/css" href="/work/css/main.css">
	<link rel="stylesheet" type="text/css" href="/work/css/jsontree.css">
	<script src="/work/consts.js"></script>
	<script src="/work/lang/ru.js"></script>
	<script src="/work/js/main.js"></script>
	<script src="/work/js/jsontree.min.js"></script>
	<script src="/work/js/apirequest.js"></script>
	<script src="/work/js/apiTestRequest.js"></script>
	<script src="/work/js/http_request.js"></script>
</head>
<body>
	<div class="wrapper">
		<?php include __DIR__ . '/header.phtml' ?>
		<div class="content">
			<div class="column">
				<?php if ($user->hasRightTo('testApi')) { ?>
				<div id="content" class="paper-list no-padding">
					<div class="paper-head"><?=Lang::getText('apiTestMethodRequest')?></div>
					<div class="p12">
						<table class="w100 no-padding">
							<tbody>
								<tr>
									<td class="left-part">
										<label class="no-margin-bottom" for="apiMethod"><?=Lang::getText('apiMethod');?></label>
									</td>
									<td class="right-part">
										<input type="text" class="text-field" placeholder="<?=Lang::getText('apiMethodSample')?>" id="apiMethod">
									</td>
								</tr>
								<tr>
									<td class="left-part">
										<label class="no-margin-bottom" for="apiRequestParameters"><?=Lang::getText('apiRequestParameters')?></label>
									</td>
									<td class="right-part">
										<textarea class="text-field textarea" placeholder="<?=Lang::getText('apiRequestParametersSample')?>" id="apiRequestParameters"></textarea>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="paper-foot">
						<button onclick="onSendButtonClick()" class="button-red right-hand-side"><?=Lang::getText('send')?></button>
					</div>
				</div>
				<div class="paper-list no-padding" style="margin-top: 24px">
					<div class="paper-head"><?=Lang::getText('response')?></div>
					<div class="p12" style="height: 100px; text-align: center; box-sizing: border-box;" id="response-container">
						<span class="gray" style="line-height: 76px">
							<?=Lang::getText('performRequestFirst')?>	
						</span>
					</div>
				</div>
				<?php } else { ?>
					<div class="paper-list no-padding">
						<div class="paper-head"><?=Lang::getText('accessError')?></div>
						<div class="notification-window"><?=Lang::getText('haveNoRightsToViewThisPage')?> 
							<div style="display:inline-block; height:30px;">
								<button class="button-red" onclick="goToMainPage()">На главную</button>
							</div>
						</div>
					</div>
				<?php } ?>
			</div>
		</div>
	</div>
</body>
</html>
