<!DOCTYPE html>
<html lang="ru">
<head>
	<title><?=Lang::getText('testRequest')?> | <?=Lang::getText('forAdmins')?></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/work/css/float-dropdown-menu.css">
	<link rel="stylesheet" type="text/css" href="/work/css/main.css">
	<script src="/work/consts"></script>
	<script src="/work/lang/ru"></script>
	<script src="/work/js/main.js"></script>
	<script src="/work/js/apirequest.js"></script>
	<script src="/work/js/apiTestRequest.js"></script>
	<script src="/work/js/http_request.js"></script>
</head>
<body>
	<div class="wrapper">
		<header>
			<div class="headline-wrapper">
				<div class="headline-elements-container">
					<div class="partitions">
						<span class="headline-elem"><a href="/main"><?=Lang::getText('mainPage')?></a></span>
						<?php if ($user !== false) { ?><span class="headline-elem"><a href="/learn"><?=Lang::getText('learn')?></a></span><?php } ?>
						<span class="headline-elem"><a href="#"><?=Lang::getText('INeedHelp')?></a></span>
						<span class="headline-elem"><a href="#"><?=Lang::getText('aboutUs')?></a></span>
						<span class="headline-elem"><a href="/bugtracker"><?=Lang::getText('bugtracker')?></a></span>
						<a href="/index" id="goToMainPage" hidden></a>
					</div>
				</div>
				<div class="account-settings">
					<?php if ($user === false) { ?>
						<span class="headline-elem">
							<a href="/login"><?=Lang::getText('logIn')?></a>
						</span>
						<div class="dropdown-lang-select" style="float:right;">
							<button class="dropbtn russian">&#160;</button>
							<div class="dropdown-content">
								<a class="english" href="#">&#160;</a>
								<a class="russian" href="#">&#160;</a>
								<a class="belarusian" href="#">&#160;</a>
							</div>
						</div>
					<?php } else { ?>
						<span class="headline-elem">
							<a href="#" onclick="goOut()" class="mr10px"><?=Lang::getText('exit')?></a>
							<img class="profile-pic" src="<?=$user->getProfilePicture()?>">
						</span>
					<?php } ?>
				</div>
			</div>
		</header>
		<div class="content"><div class="column">
				<?php if ($user->hasRightTo('testApi')) { ?>
				<div id="content" class="paper-list no-padding">
					<div class="paper-head"><?=Lang::getText('apiTestMethodRequest')?></div>
					<div class="p12">
						<table class="w100 no-padding">
							<tbody>
								<tr>
									<td class="left-part">
										<label class="no-margin-bottom" for="apiMethod"><?=Lang::getText('apiMethod');?></label>
									</td>
									<td class="right-part">
										<input type="text" class="text-field" placeholder="<?=Lang::getText('apiMethod')?>" id="apiMethod">
									</td>
								</tr>
								<tr>
									<td class="left-part">
										<label class="no-margin-bottom" for="apiRequestParameters"><?=Lang::getText('apiRequestParameters')?></label>
									</td>
									<td class="right-part">
										<textarea class="text-field textarea" placeholder="<?=Lang::getText('apiRequestParametersSample')?>" id="apiRequestParameters"></textarea>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="paper-foot">
						<button onclick="onSendButtonClick()" class="button-red right-hand-side"><?=Lang::getText('send')?></button>
					</div>
				</div>
				<?php } else { ?>
					<div class="paper-list no-padding">
						<div class="paper-head"><?=Lang::getText('accessError')?></div>
						<div class="notification-window"><?=Lang::getText('haveNoRightsToViewThisPage')?> 
							<div style="display:inline-block; height:30px;">
								<button class="button-red" onclick="goToMainPage()">На главную</button>
							</div>
						</div>
					</div>
				<?php } ?>
			</div>
		</div>
	</div>
</body>
</html>
